name: Tests

on:
  push:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          mypy pylint

      - name: Run mypy to generate cache
        run: mypy pylogger || true

      - name: Install missing stub packages
        run: mypy --install-types --non-interactive

      - name: Run mypy
        run: mypy pylogger

      - name: Run pylint
        run: pylint pylogger
